### ISSUE TITLE
Brak id a11y-architektura

### ISSUE THREAD

**Issue by JacZad** [posipa/a11yjson#3]
W wygenerowanej deklaracji dostępności brakuje atrybutu obowiązkowego. To też zgłosił mi Grzegorz, a ja sprawdziłem. Faktycznie - nie ma.

**Comment by posipa** [comment]
zrobione 
https://github.com/posipa/a11yjson/blob/ebc0795c2735709f6efaf80e34c816ae9b8e2dfc/model/arch/arch.json#L5
